# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('event_type', models.SmallIntegerField(choices=[(1, 'Wedding'), (2, 'Ball'), (3, 'Conference')])),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.City')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('capacity', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Place'),
        ),
    ]
