# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='users.BaseUser')),
                ('signature', models.ImageField(
                    blank=True,
                    null=True,
                    upload_to='teachers_signatures')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.baseuser',),
        ),
    ]
